# Generated by Django 5.1.2 on 2024-11-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='raw_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
